### ISSUE TITLE
Training on other datasets

### ISSUE THREAD

**Issue by RobsoUganda** [ChantalMP/RaDialog_v2#1]
Hello, thanks for the good work. can one train the model of various datasets like for MRI brain, cardiac CT, Medpix, mammo ,etc....

**Comment by ChantalMP** [comment]
Hi, yes, you can adapt it to other data modalities. You would need to change the image encoder and generate a dataset for your use case.

**Comment by RobsoUganda** [comment]
Thank you so much for the response. can you direct me to any particular code i can change and i have a look at it

**Comment by ChantalMP** [comment]
For the dataset creation you can take a look here: https://github.com/ChantalMP/RaDialog/blob/master/data/create_data.py However, this is of course very specific for our usecase. In the end what you need is to create a json file following the LLaVA training data format.
Regarding the image encoder, you have to change the vision_tower in the LLava model, one place to start is here:
https://github.com/ChantalMP/RaDialog_LLaVA/blob/master/LLAVA/llava/model/builder.py#L164
But you need to change some other places that are related to the vision tower.

**Comment by RobsoUganda** [comment]
That is great, can this model handle both 2D and 3D images with interleaved texts?

**Comment by ChantalMP** [comment]
The image encoder we are using currently is a 2D-only encoder. For 2D+3D you will have to adapt it, but in theory that should be possible.

**Comment by RobsoUganda** [comment]
can the mode support the upload of multiple images? in VQA form

**Comment by ChantalMP** [comment]
Not natively.
