### ISSUE TITLE
About Rad-ReStruct

### ISSUE THREAD

**Issue by wwxxyy1996** [ChantalMP/RaDialog_v2#3]
Hello, thank you for your work! I noticed that you have been training on Rad-ReStruct. Could you please let me know if there is a paper published with the related results? Additionally, would it be possible to share the dataset or the process of converting Rad-ReStruct into a QA format? Thanks in advance!

**Comment by ChantalMP** [comment]
Hi,
we evaluated the results on Rad-ReStruct, but currently there is no paper publically available. However, I can share the results on the test set with you here in case you are interested:
![Screenshot 2024-11-04 at 09 51 53](https://github.com/user-attachments/assets/16072f10-e68f-43c6-a523-cbe7429e7048)

Regarding the conversion, we include the history of a question as a conversation of question-answer pairs. For the current question, we include the possible answer options in the prompt.
