### ISSUE TITLE
About the "Assistant:"

### ISSUE THREAD

**Issue by Eldo-rado** [ChantalMP/RaDialog_v2#4]
Thank you for your contribution. 
I’d like to ask: when training based on the LLava weights, does the output include "Assistant:"? Like LLava, I included "Assistant:" as part of the output during training, but it never appears in my results.

**Comment by ChantalMP** [comment]
Hi :) 
yes, the conversation training data does include "Assistant", for inference ASSISTANT: is the last part of the input prompt and then the generation starts after that.
