### ISSUE TITLE
Checkpoints without the CheXpert Inputs

### ISSUE THREAD

**Issue by wjhou** [ChantalMP/RaDialog_v2#5]
Hi, 

Thanks for your contributions in releasing the checkpoints and datasets.

Since these checkpoints (including Vicuna and LLaVA) take the CheXpert predictions as inputs, they have some difficulties applying them to other settings in radiology report generation. 

I want to inquire whether you have the pure LLaVA checkpoints that only take images as inputs and report as outputs.

Best Regards,
Ethan

**Comment by ChantalMP** [comment]
Hi,

as we showed in the paper, the CheXpert findings have a significant influence on the performance. Therefore we do not plan to publish a version without. However, for all settings within the chest-x-ray domain, the chexpert predictions can be computed at inference-time using the chexpert labeler checkpoint.

Best regards,

Chantal
